### ISSUE TITLE
Wo ist der Unterschied zwischen Mediengestaltung/Medieninformatik?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#133]

**Comment by thugpanda** [comment]
*Digitale Medien* ist ein gemeinsamer Studiengang der HfK und Uni Bremen. An den beiden Institutionen wird je ein Studienprofil angeboten — *Mediengestaltung/Media Design* im Bachelor/Master of Arts an der HfK & *Medieninformatik/Media-Informatics* im Bachelor/Master of Science an der Universität.
Das Studienprofil regelt neben dem Abschluss auch gewissermaßen die grobe Richtung, in der sich die Spezialisierung im Laufe des Studiums ansiedeln wird. Unterschiede in den Modulplänen sorgen für die Auseinandersetzung mit verschiedenen Fachrichtungen. Dieser Struktur kann strikt gefolgt werden, aber auch jederzeit ohne Probleme Module aus der dem anderen Studienprofil belegt werden.

Details dazu gibt es am Dienstag, 9.10., in der HfK.
