### ISSUE TITLE
JETZT: Kaffee and Kuchen 🍰 MZH 1090 

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#140]

**Comment by thugpanda** [comment]
Die Begrüßung durch den Rektor ist eine Veranstaltung, die sich nur an Studierende der HfK richtet. Dementsprechend ist der Punkt für Studierende des Profiles Medieninformatik nicht relevant.

Unser gemeinsames Programm des Studienganges startet am Montag um 12.00 Uhr in der HfK. MI-Studierende sind aber herzlich eingeladen, bereits um 11 Uhr zu kommen und die Anderen bei einem kleinen Bruch schon mal kennenzulernen.

**Comment by jelko** [comment]
Oh man, das Bierchen haben wir uns aber verdient.

Die Kneipentour beginnt heute (Di) Abend in der [Capri Bar (Fehrfeld 35, 28203 Bremen)](https://goo.gl/maps/sQ8uGvKfxKU2). Das ist im "Bermuda Dreieck". Wenn ihr mit der Bahn unterwegs seid: Steig beim _Sielwall_ (Line 2,3,10) aus.

**Comment by the-leonat** [comment]
![6ec81f3d-cf26-48fd-b0c2-b3d2b0ec90dd](https://user-images.githubusercontent.com/3268017/46726465-b76b2c80-cc7e-11e8-9f0d-22a3786b717a.jpeg)
