### ISSUE TITLE
NOW: Coffee and Cake 🍰 MZH 1090 

### ISSUE THREAD

**Issue by jelko** [digitalmediabremen/hej#146]

**Comment by jelko** [comment]
Oh man, das Bierchen haben wir uns aber verdient.

Die Kneipentour beginnt heute (Di) Abend in der [Capri Bar (Fehrfeld 35, 28203 Bremen)](https://goo.gl/maps/sQ8uGvKfxKU2). Das ist im "Bermuda Dreieck". Wenn ihr mit der Bahn unterwegs seid: Steig beim _Sielwall_ (Line 2,3,10) aus.

**Comment by mitje** [comment]
Current location Lagerhaus

**Comment by mitje** [comment]
New Location: Wiener Hofcafe and Lift

**Comment by the-leonat** [comment]
![0605d4fb-c6dc-4290-ae49-07979158ede4](https://user-images.githubusercontent.com/3268017/46727161-3a40b700-cc80-11e8-9d1f-d77efde541e8.jpeg)
