### ISSUE TITLE
Dienstag um 10 oder um 11? Um 11 für Bachelor!

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#150]

**Comment by jelko** [comment]
Wo auch immer stand (wo denn?), dass die Veranstaltung für Bachelor um 10 sei. Sorry. Sie ist um 11! Ihr könnt länger schlafen – ist ja klar. Claudia Kessler sagt dann was zur Struktur des Studiums. Ihr solltet kommen, denn es wird helfen den ganzen Laden zu verstehen. Ahoi!

PS: Wir sind im Viertel. (23:32)
