### ISSUE TITLE
Wie kann ich meinen E-Mail Account in meinem Mail-Client einrichten?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#155]

**Comment by jelko** [comment]
Für deinen HfK Account stellt dir das [Dezernat 5](http://www.hfk-bremen.de/t/dezernate/n/dezernat-f%C3%BCr-controlling-und-it) die Informationen für IMAP + SMTP zur Verfügung. [Diese Anleitung](http://www.hfk-bremen.de/sites/default/files/media/einrichtendesoutlook2007clients.pdf) hilft dir vielleicht weiter. Oder?!

Deinen Uni-Account kannst du natürlich gleichermaßen mit deinem PC oder Telefon verbinden. Das [ZFN hat alle Informationen](https://www.uni-bremen.de/zfn/weitere-it-dienste/e-mail/e-mail-client-einrichten/) für dich.

Übrigens: Du kannst auf beiden E-Mail Servern eine Weiterleitung, auf eine Private Adresse oder die der anderen Uni, einrichten. Also nicht beschweren, dass du keine Uni-Mails erhältst.
