### ISSUE TITLE
Kann ich auch Kurse Abseits der fünf Grundlagenveranstaltungen wählen, die im Stundenplan stehen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#158]

**Comment by jelko** [comment]
Deine Frage war: Als DM MG, 1. Semester, inwiefern spielen Module abseits der 5 Kurse eine Rolle für uns, sind weitere Sachen wählbar?

Eine gute Frage! Du kannst selbstverständlich auch Kurse aus vermeintlich höheren Semestern wählen. Der Studienverlaufsplan ist nur ein Vorschlag, an den du dich nicht starr halten musst. Es kann ganz Interessant sein über allein einen Jahrgang hinweg zu studieren. Wenn du also Intresse an den Angeboten hast, gehe zum ersten Termin und schau es dir an. Mach nur [nicht zu viel](http://hej.digital/165) in einem Semester, das bringt meist nichts. _PS: Nächstes Semester, gibt's wieder verlockende Angebote._
