### ISSUE TITLE
Wo finde ich die ganzen Modulebeschreibungen und -anmeldungen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#166]

**Comment by jelko** [comment]
Freunde, das ist gar nicht so schwer.

Der Modulplan und -katalog ist auf der Website des Studiengans zu finden: Einmal als [Studienverlaufsplan](http://digitalmedia-bremen.de/profile/bachelor/program-structure/) (was nur ein Vorschlag und keine Regel ist) und dann als Teil der [Prüfungsordnung](http://digitalmedia-bremen.de/profile/bachelor/regulations/) als Modulkatalog (das sind die eigentlichen Regeln).

Wenn es allerdings um konkrete Kure, und nicht Module, geht, dann müsst ihr in die [Vorlesungsverzeichnisse](http://hej.digital/course-catalog) schauen. Dort stehen für die jeweiligen Semester alle Veranstaltungsangebote, die Beschreibungen dazu und in welche Module "sie passen".

Die Anmeldung zu den Kursen kann über ARTIST bzw. Stud.IP (dann später PABO) durchgeführt werden. Notwendig ist das aber erst einmal nicht. Ihr könnt einfach zu den Veranstaltungen beim ersten Termin hingehen. Die verbindliche Anmeldungen zu den Kursen sind erst zum Ende des Semesters wichtig.

Beantwortet das deine Frage? Sonst frag noch mal! ;)
