### ISSUE TITLE
Bei mehreren Terminen des selben Kurses (z.B. Mathe) auf dem Plan, muss ich alle Termine besuchen oder nur einen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#168]

**Comment by WesamEnj** [comment]
Immer von _dem Kurs abhängig_. Bei **Mathe** sind das wöchentlich 2 Vorlesungen und eine Übung die besuchen sollte. Bei den **Gestalerische Grundlagen** Kursen muss man sich nur für eins der unterschiedlichen Angebote entscheiden.
