### ISSUE TITLE
UPDATED (neuer Plan) Wie schreibe ich mich für die Tutorien für PI, MI und Mathe ein?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#170]

**Comment by jelko** [comment]
Wir leiten euch die Infos vom Studienzentrum Informatik (SZI), das die Koordination der Veranstaltungen durchführt weiter:

Es wird gebeten sich in Stud.IP zusätzlich zu den einzelnen Veranstaltungen (PI, MI und Mathe) für [Tutorieneinschreibung Erstsemester](https://elearning.uni-bremen.de/dispatch.php/course/details/?sem_id=82eb799823097d24eeb835686d456ada&send_from_search=1&send_from_search_page=https%3A%2F%2Felearning.uni-bremen.de%2Fdispatch.php%3Fkeep_result_set%3D1) anzumelden, damit darüber die Zuordnung stattfinden kann.

Dort wird ein [Stundenplan](https://www.szi.uni-bremen.de/wp-content/uploads/2018/07/DM.pdf) mit geeigneten Tutoriumsterminen für Studierende aus den Digitalen Medien angeboten. Das ist bestimmt ein guter und sinnvoller Vorschlag. Eigene Lösungen sind selbstverständlich immer möglich. Wendet euch bei Fragen direkt an Sabine Kuske vom [Studienzentrum](mailto:studienzentrum@informatik.uni-bremen.de).

**Comment by jelko** [comment]
Ab Dienstag, dem 9.10.18 um 12:00 bis Donnerstag, dem 11.10.17 um 14:00 könnt Ihr Erstsemester Euch hier für einen Stundenplan eintragen. Die Stundenpläne (für DM gibt es nur einen) könnt Ihr Euch unter Dateien ansehen.

**Digitale Medien Studierende müssen sich also allein bei Stud.IP in die [Gruppe "Digitale Medien (X/X)"](https://elearning.uni-bremen.de/dispatch.php/course/statusgroups?cid=82eb799823097d24eeb835686d456ada&contentbox_open=e64b3b44b378a62bcda8b6bc94656b77#e64b3b44b378a62bcda8b6bc94656b77) eintragen, wenn ihr den Standardstundenplan annehmen wollt.**

## Wie trage ich mich für einen Stundenplan ein?
1. Auf Teilnehmende klicken (Teilnehmende befindet sich oben.)
2. Gruppen anklicken (Gruppen befindet sich links.)
3. In eine Gruppe eintragen anklicken (In eine Gruppe eintragen befindet sich ebenfalls links.)
4. Die gewünschten Gruppe auswählen und auf Beitreten klicken

WICHTIG: Tragt Euch bitte schon jetzt unter Stud.IP für die Lehrveranstaltungen ein, die Ihr dieses Semester besuchen werdet. (Sonst können Euch die Lehrenden nicht gemäß Eures gewählten Stundenplans in die Übungsgruppen eintragen.)
 
## Wie trage ich mich für eine Lehrveranstaltung ein?
1. In das Suchfeld oben rechts klicken. Dann Enter-Taste drücken. Es öffnet sich eine ausführlichere Suchmaske. 
2. Die gewünschte Veranstaltung  eingeben; zum Beispiel: Theoretische Informatik 1: Endliche Automaten und formale Sprachen (dabei darauf achten, dass das Semester WS 18/19 eingestellt ist)
3. Links auf Zugang zur Veranstaltung klicken

Bei Fragen wendet Euch bitte per E-Mail an studienzentrum@informatik.uni-bremen.de
