### ISSUE TITLE
Muss ich beide Vorlesungen (Di + Do) in Praktische Informatik belegen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#173]

**Comment by jelko** [comment]
Ja. In Mathe und PI finden zwei Vorlesungen wöchentlich statt. Andernfalls, wäre die Wahlmöglichkeit angegeben. Deswegen werden diese Veranstaltungen auch mit 8 CP (und nicht den üblichen 6 CP) angerechnet.
