### ISSUE TITLE
Wo findet man die Facebook Gruppen, von denen schon mal die Rede war?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#174]

**Comment by mitje** [comment]
Es gibt zwei relevante Studiengangsgruppen 
facebook.com/groups/DMBachelor2018 exklusiv euer Jahrgang
facebook.com/groups/DMUniBremen exklusiv DM Studis der Kooperation aber alle Jahrgänge
Eine FB Gruppe die Digital Media Bremen heißt ist nicht exklusiv, dort sind auch Alumnis, Arbeitgeber und was sich sonst noch für DM in Bremen interessiert drin.
