### ISSUE TITLE
Digital Fabrication Workshop für Studentinnen – Wie melde ich mich an?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#176]

**Comment by jelko** [comment]
Ankündigung des SZI:

Der Workshop bietet weiblichen Studierenden die Möglichkeit, im FabLab hands-on Informatik zu machen. Es wird ein gesamter Prozess von der Problemstellung über Programmierung bis zur Präsentation des fertigen Produkts durchlaufen. Die Studentinnen stellen nach ihren eigenen Vorstellungen und Ideen ein Objekt für sich selbst her.

Der Workshop richtet sich explizit an Frauen mit der Absicht, sich untereinander kennenzulernen und gleichzeitig die kreative Seite der Informatik auszuleben.

Wenn möglich bitte eigenen Laptop mitbringen und gerne Processing vorher installieren.

Datum:

12.10.2018, 12:00 – 16:00 Uhr (vorrangig für den Studiengang Digitale Medien)
Ort: GW2, A4100 (FabLab der Universität Bremen)

Der Workshop wird angeboten von [Nadine Dittert](http://dimeb.informatik.uni-bremen.de/index.php?id=217). Die Anmeldung erfolgt über den [Stuga DM](mailto:stugadm@informatik.uni-bremen.de) per E-Mail.
