### ISSUE TITLE
TIMETABLE ab Montag 2017-10-09

### ISSUE THREAD

**Issue by thugpanda** [digitalmediabremen/hej#20]

**Comment by thugpanda** [comment]
![hej_handzettel_2017_v13](https://user-images.githubusercontent.com/19735292/31160182-d659980e-a8ce-11e7-9024-46e0b1f16936.png)

**Comment by jelko** [comment]
![hej_handzettel_2017_v13](https://user-images.githubusercontent.com/19735292/31160290-a722b650-a8cf-11e7-868e-f84aa0bb9bc0.png)
