### ISSUE TITLE
Gibt es schon Termine für die ganzen fun activities?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#209]

**Comment by LisaSpetzler** [comment]
Yes! Am Montag werden wir uns nach der DM Begrüßung gemütlich in der HfK zusammensetzen, am Dienstag um 20 Uhr geht's los mit der Kneipentour in der Capri Bar, Donnerstag um 21 Uhr gibt es eine Hochschulanfangsfeier im Magazinkeller und den krönenden Abschluss bildet die Semester Opening Party mit Radio Angrezi am Freitag um 20 Uhr in der Flut (bei der Speicherpassage in der HfK). Wir freuen uns auf euch!
