### ISSUE TITLE
Wann beginnt die Orientierungswoche für mich? Gibt es einen eigenen Plan für Medieninformatiker?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#217]

**Comment by thugpanda** [comment]
Die Orientierungswoche beginnt für alle DM-Studierende am Montag, den 07.10.2019 in der HfK. Da Digitale Medien ein gemeinsamer Studiengang der HfK und Universität ist, gibt es auch eine gemeinsame Orientierungswoche. In deinem Studium wirst du schließlich auch Kurse an der Uni und HfK belegen.
