### ISSUE TITLE
Schedule (07.-11. October)  

### ISSUE THREAD

**Issue by LisaSpetzler** [digitalmediabremen/hej#224]

**Comment by WesamEnj** [comment]
Test Test Teeeest**jkkk**

**Comment by WesamEnj** [comment]
### MONDAY

**_14:30 Welcoming to Digital Media_**
Some professors will show some inspiring and interesting projects from previous Master Students. Also we, the hej.digital team, will introduce ourselves for the first time! So say hej to us! We’re looking forward meeting you. 
_WHERE? University of the Arts (Speicher XI) Theory Room – 4 15.070_
 

**_15:30 Hej, are you not entertained? 🤓_**
After the main programme we warmly invite you to stay a little longer. There will be some drinks, bread and selfmade hummus and a futuristic playground (e.g. VR to try, whohoo).
_WHERE? Theory Room – 4 15.070_

### TUESDAY

**_10:00  Informations on structure & organisation of the study_**
Curriculum, modules, enrollment for classes on the universities, access to both systems etc. Use the chance to ask some questions at the end. We’re gonna be there too.
_WHERE? University of the Arts (Speicher XI), Auditorium_
  
**_11:00 HfK Tour_**
Mahshid will show you the most important or interesting spots in the HfK! The coffee brewer, the kitchen, secret passageways to Narnia! 🦙

Tipp: If you want you can eat something in the Mensa! - Bring cash for that.

**_13:00 Introduction of the classes_**
Opening of the semester by dean of the faculty Art and Design and spokespersons of the  programme, show of »merits« of last semester and of the courses of your fresh semester.

_WHERE? University of the Arts (Speicher XI), Auditorium_

**_20:00 Digital Media Pub Crawl 🍻_**

_WHERE? At Capri Bar!_
If you can’t find us, just write us here on hej.digital!

### WEDNESDAY

**_10:00 Keys, Cards + Breakfast_**
Accesschips for University & something nice to eat

_WHERE? University, MZH 1400_

Tips:
Bring 15€ and your ID!
There are “VIP-seats” in the Mensa from 12:15!

**_13:15 Campustour_**
Get to know the campus and its secret paths, also most important places. There will be a shopping trolley full of drinks and a very tired but top motivated hej.team! 🏋🏼‍♂️

_WHERE? University, Entry of MZH_

**_15:00 Coffee, coffee, coffee 🍪☕️_*
 Just a calm event to chill with each other and eat cookies. 

_WHERE? University, MZH 1470_

### THURSDAY

**_9:00 Workshoptour (MD)_**
For profile Media Design!
Mahshid is showing you all workshops, now you can start experimenting and working!
  
_WHERE? University of the Arts (Speicher XI), Foyer_

**_14:00 Computation Services (MI)_**
For profile Media Informatics!
Introduction into the IT-infrastructure of the University with Sandor. And many important things. Whoopwhoop! 🤓

_WHERE? University; MZH 1400_

**_21:00 HAnF-Party_**
A semester opening party from the FB3! Finally!

_WHERE? Magazinkeller!_

### FRIDAY

**_12:00 Questions, Answers & Tips for DM-Students_**
With us, from the hej.digital team! Yay! 🚀
We explain everything you need to know about important facilities, experiences from the programme & other helpful things. There will also be guests to give you some last tips for your studies. 
Here you have the chance to ask everything that hasn’t been answered just right!

_WHERE? University; MZH 1100_


**_15:00 Introduction to the Library_**
The library, study room, printing and copying & cyber-access via VPN

_WHERE? University, SuUB (Library) Foyer_

**_20:00 The One Thousand Reasons Party brought to you by Radio Angrezi !!!_**
The marvelous culmination is going to be a party which has many reasons. We’ve got new, wonderful people joining us at both universities, the new semester should be started and celebrated properly, the HfK Radio Agrezi is having its first birthday and moved into a new studio and so on… Come by and let’s finish this week off together with some live music, installations and some nice tunes.
_WHERE? University of the Arts (Speicher XI),  Flut und Nebenflut_
