### ISSUE TITLE
Wo kann ich die Zugangsdaten für den Rechnerpool in EO des MZH bekommen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#24]

**Comment by laura-meyer** [comment]
Die Zugangsdaten für den Rechnerpool solltest du zusammen mit deiner Immatrikulationsbescheinigung zugeschickt bekommen haben. Dort solltest du den Nutzernamen und das Passwort finden,  solange du diese nicht schon manuell (nach der beigefügten Anleitung) geändert hast.
Falls du diese nicht bekommen hast, könntest du versuchen das Schreiben im SfS (Sekretariat für Studierende I'm Verwaltungsgebäude) zu bekommen.
