### ISSUE TITLE
Wo meldet man sich für die Kurse an der HfK an? 

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#242]

**Comment by LisaSpetzler** [comment]
Die Kurse an der HfK werden nicht bei Stud.IP, sondern bei einem Portal namens Artist gewählt.
Detaillierte Informationen gibt es am Dienstag um 11.00 im Auditorium in der HfK in der Veranstaltung mit Studiengangskoordinatorin Claudia Kessler.
