### ISSUE TITLE
Zu welchen Modulen gehören die Kurse "Formelwelten", "OPIUM"?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#243]

**Comment by WesamEnj** [comment]
Die zwei Kurse sind das Angebot des interdisziplinären Moduls dieses Jahres. _Was das interdisziplinäre Modul ist?_  
Das ist das Modul, wo Studierenden beider Profilrichtungen (MI + MG) zusammen im Rahmen eines gemeinsamen Kurses arbeiten, betreut von Lehrenden sowohl der Uni, als auch der HfK.
