### ISSUE TITLE
Wie melde ich mich zu Veranstaltungen in ARTIST an?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#248]

**Comment by jelko** [comment]
Für Digitale Medien Veranstaltungen: portal.hfk-bremen.de > ARTIST > Meine Veranstaltungen > [An-/Abmelden](https://portal.hfk-bremen.de/myartist/mycourses/Seiten/registration.aspx)

Für alle anderen Veranstaltungen (aus anderen Studiengängen): Du kannst Dich durch das Campus Office (mailto:campus-office-kud@hfk-bremen.de) eintragen lassen. Die Veranstaltung taucht dann bei dir in ARTIST auf.
