### ISSUE TITLE
🍻Wann findet die Kneipentour statt? Wo geht's dann hin?🍻

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#251]

**Comment by WesamEnj** [comment]
Die Kneipentour fängt **heute Dienstag** um 20 Uhr bei der _Capri Bar_ an. Pünktlich ankommen, denn die **Happy Hour** geht nur von 20 bis 21 Uhr. 
Wo es danach mit uns hingeht, kann man [hier](https://docs.google.com/document/d/1E_uCNX3q4r6fl9z7J2Q0qqtYHdE0pPvIgtHERnRaVDs/edit?usp=sharing) verfolgen, falls man irgendwann Kontakt mit anderen verliert. 
Oh, und um 23 Uhr beginnt der **Studi-Dienstag** im _Tower_. [Hier](https://docs.google.com/document/d/1NZK7RkTdJt1RlHe0bl4TggpICLTwwl39blzRlX0OJpE/edit?usp=sharing) sind die 10 Menschen, die den QR Code verfolgt haben, und sich damit auf die Gästeliste eingetragen haben.
