### ISSUE TITLE
Studienschwerpunkte MI / MG

### ISSUE THREAD

**Issue by jelko** [digitalmediabremen/hej#26]

**Comment by laura-meyer** [comment]
Die Studienschwerpunkte sind teilweise festgelegt, doch bieten auch viel Spielraum.
Gerade in den für die ersten Semester empfohlenen Kursen sind die Einschränkungen zu sehen wie Mathe oder Praktische Informatik für Medieninformatik (MI) und Programmieren für Gestalter für Mediengestaltung (MG).
Wenn ihr euch den Modulplan anguckt, seht ihr, dass dieser große Wahlmodule wie Spezielle Gebiete der Digitalen Medien oder Wahl für Medieninformatik / Mediengestaltung bietet. In diesen könnt ihr sowohl Kurse der HfK als auch der Uni einbringen. Hierfür gibt es eine in der Prüfungsordnung  festgehaltene Maximalanzahl an Credit Points, die ihr an der jeweils anderen Hochschule einbringen dürft.

Kann der Schwerpunkt gewechselt werden?
Dies ist sofern möglich, dass ihr die Hochschule wechselt und euch an der jeweils anderen immatrikliert. Aber Achtung! Hierfür müsst ihr euch jeweils zum Wintersemester für das normale Bewerbungsverfahren bewerben und angenommen werden. Die Kurse, die ihr bereits belegt habt, können dann teilweise (je nachdem wie passend sie zu den Modulen der jeweils anderen Hochschule sind) anrechnen lassen.
