### ISSUE TITLE
Soll man sich nach der O-Woche bei Studip von den Veranstaltung "Fachbereichs Netze" und "Tutorieneinschreibung Erstsemester" abmelden?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#265]

**Comment by WesamEnj** [comment]
Von _Fachbereichsnetze_, ja. Allerdings ist _Tutorieneinschreibung Erstsemester_ noch für die ersten Wochen notwendig, also bitte nicht abmelden.
