### ISSUE TITLE
Wer darf alles auf die Hochschulanfangsfeier H.A.n.F.? // Who's welcome at the Hochschulanfangsfeier H.A.n.F.?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#29]

**Comment by laura-meyer** [comment]
Die Hochschulanfangsfeier findet am Donnerstag, den 12. Oktober ab 21.00 Uhr im Magazinkeller (am Schlachthof in der Nähe vom Hauptbahnhof) statt. Die Party wird primär vom Fachbereich 3 organisiert, doch sie ist öffentlich und jeder ist willkommen.
In den letzten Jahren sind auch sind auch die unterschiedlichsten Leute gekommen - sowohl von der Uni als auch von der Hochschule für Künste oder der Hochschule. Auch so einige aus anderen Studiengängen außerhalb des Fachbereichs 3 haben vorbei geschaut.
