### ISSUE TITLE
Wie wird das Hybrid-Semester aussehen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#296]

**Comment by simonslang** [comment]
COVID-19 hat unser Studium grundlegend verändert! Neue Formen der Lehre, Digital sowie in Zukunft auch Physisch, entstehen, sowie neue Formen der Kommunikation und Zusammenarbeit. Nach einem rein digitalen Sommersemester folgt nun ein "Hybrid"-Semester im Winter in welchem ihr euer Studium startet. 

Das Hybridsemester soll zum Teil Digital sowie zum Teil in Präsenz stattfinden. In Welcher Form die von euch belegten Kurse stattfinden erfahrt ihr bei Anmeldung über [StudIP](https://elearning.uni-bremen.de) und [ARTIST](http://hej.digital/248) 

Allgemeine Informationen wie das kommende Semester aussehen wird findet ihr hier:

[Uni](https://www.uni-bremen.de/informationen-zur-corona-pandemie)
[HfK](https://www.hfk-bremen.de/corona-info)

Wir Studierende sind seit Beginn der "Krise" aktiv und versuchen stetig die Studienbedingungen unter den neuen Umständen zu verbessern. Vieles darüber wie das kommende Semester aussehen wird ist weder uns noch den Dozenten wirklich klar und wird sich auch erst mit Beginn der Vorlesungen manifestieren. Wir können alles verändern - wenn du also selbst aktiv werden möchtest schau doch mal [hier](http://hej.digital/134)
