### ISSUE TITLE
📅 Important Dates

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#298]

**Comment by simonslang** [comment]
We know, beginnings are confusing! So here are the most important dates for your start:

**19.10** Official semesterstart HfK (Don't mind this one - it's just a random date someone has decided on)

**26.10-30.10** Orientation week Digital Media (Doesn't matter if you are at the university or HfK, this is a joint affair! And the first thing which is really important!)

**1.11** Official semesterstart University

**2.11** Beginning of courses (Before that there is no teaching)
