### ISSUE TITLE
Welche Veranstaltungen sind verpflichtend?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#31]

**Comment by jelko** [comment]
Im Studium sind **Pflichtveranstaltungen** und **Wahlpflichtveranstaltungen** zu absolvieren. Pflichtveranstaltungen liegen im **[Studienverlaufsplan](http://digitalmedia-bremen.de/de/profil/bachelor/struktur-des-studiums/)** in den ersten Semestern. Wahlmodule (in denen ich aus mehreren Angeboten wählen kann) kommen vermehrt zum Ende des Studiums. (Der Studienverlaufsplan ist jedoch nur ein (sinnvoller) Vorschlag und muss nicht zwangsläufig eingehalten werden. )

In den beiden Studienrichtungen MI und MG unterscheiden sich die Pflichtveranstaltungen ein wenig.

Im **ersten Semester** kannst/solltest du folgende Veranstaltungen besuchen:

### Profil: Medieninformatik (MI)

- Gestalterische Grundlagen 1 (Wahlmöglichkeiten) > an der HfK
- Mathematische Grundlagen 1 > an der Uni
- Grundlagen der Medieninformatik > an der Uni
- Medienwissenschaften 1 > an der HfK
- Praktische Informatik 1 > an der Uni

### Profil: Mediengestaltung (MG)

- Gestalterische Grundlagen 1 (Wahlmöglichkeiten) > an der HfK
- Grundlagen der Medieninformatik > an der Uni
- Medienwissenschaften 1 > an der HfK
- Programmieren für Gestalter > an der Uni

Den gesamten Studienverlaufsplan und Beschreibungen zu den Modulen (das ist ein "Platz" für einen konkreten Kurs) findest du hier: http://digitalmedia-bremen.de/de/profil/bachelor/struktur-des-studiums/

*noch nicht alle Fragen beantwortet? Stell noch eine und wir ergänzen die Informationen.*
