### ISSUE TITLE
All changed information about the semester abroad

### ISSUE THREAD

**Issue by simonslang** [digitalmediabremen/hej#319]

**Comment by LisaSpetzler** [comment]
Oh, that's a tough one! So, for all of you who missed the event where Claudia Kessler and Andreas Breiter explained the most important stuff: They are optimisticly expecting that being able to participate in a proper semester abroad will be possible in the winter semester 2021/2022 and therefore in the following summer semester. **Your application is due in January!** Yes, that seems quite early, but that's also necessary for many organizational reasons. You can find the slides from the event [here](https://digitalmedia-bremen.de/wp-content/uploads/2020/11/FolienAusland_2020.pdf) and some more useful information (including a list of partner universities) [here](https://digitalmedia-bremen.de/profile/bachelor/auslandssemester/)!
