### ISSUE TITLE
Wie unterscheidet sich der Rundgang am Mittwoch, 11.10., von der Campus Tour am letzten Mittwoch? // What's happening at the campus tour on Wednesday, 11.10.?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#33]

**Comment by thugpanda** [comment]
Der Rundgang am Mittwoch, dem 11.10., bietet mehr Inhalte und mehr Infos. Vor allem aber wird er eine lustige, entspannte, gemeinsame Aktion mit allen DMlern. Und Kuchen. Außerdem gibt es einen englischsprachigen Rundgang.

###### *EN*
*The campus tour on Wednesday, 11.10., is full of information about cool and important places on the campus. Most notably however it's a mutual meet and greet.*
*The tour is split into English and German.*
