### ISSUE TITLE
Gibt es zwei Studentenausweise und was brauche ich, um Kurse in Uni und HfK besuchen zu können? // Are there two student IDs and what is required in order to take classes at both Uni and HfK?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#40]

**Comment by thugpanda** [comment]
You only get one student ID. Which one it is depends on your studies structure - #mi get theirs from uni, #md from HfK.
However you'll get access to the platforms of both institutions. In the information about studies programme on Tuesday, 10AM for Bachelors and 11AM for Masters, further detail will be given to you.
