### ISSUE TITLE
Kann man das Studienprofil wechseln und wenn, ist das während des Semesters möglich oder nur zu Beginn des neuen Semesters?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#49]

**Comment by leonard0x** [comment]
Du kannst grundsätzlich zu jedem Semesterbeginn die Studienvertiefung wechseln, allerdings musst dafür die [Aufnahmekriterien](http://digitalmedia-bremen.de/de/profil/bachelor/bewerbung-und-zulassung/) der jeweiligen Studienrichtung erfüllen. 
Wir empfehlen dir allerdings solche Entscheidungen nicht zu eilig zu treffen sondern jetzt die Möglichkeit zu nutzen beide Vertiefungen besser kennenzulernen.
