### ISSUE TITLE
++ Get together today (Thu) 20:00 Lagerhaus 🎉🍻 ++

### ISSUE THREAD

**Issue by laura-meyer** [digitalmediabremen/hej#61]

**Comment by jelko** [comment]
Das get together startet um **20:00 im Kafé Lagerhaus (Schildstraße 12-19)**. Wir vom Team sind gerade noch voll mit der Vorbereitung der [DAO Austellung](http://hej.digitalmedia-bremen.de/57) morgen und der [Party](https://www.facebook.com/events/290905111394441) heute Abend im Magazinkeller beschäftigt. Daher werden wir erst später zu euch dazustoßen können. Ihr solltet selbstverständlich keinesfalls auf uns warten. 😉  Prost und bis später! 🍻

_Hej! The get together will start at 20:00 at Kafé Lagerhaus (Schildstraße 12-19). Most of us form the team are still preparing for the [DAO exhibition](http://hej.digitalmedia-bremen.de/57) tomorrow and the [Party](https://www.facebook.com/events/290905111394441) at Magazinkeller tonight. Therefore we will join later. Obviously you should not wait. 😉  Have a great start and see you later! Cheers. 🍻_
