### ISSUE TITLE
How can I register for courses in ARTIST?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#62]

**Comment by jelko** [comment]
You can register for courses in ARTIST at ["An-/Abmelden"](https://portal.hfk-bremen.de/myartist/mycourses/Seiten/registration.aspx). Don't worry too much about registration though, you can easily attend the first meeting of the course without registration.

_The question was: "Can I register for a course in ARTIST directly? If so, how?" Please ask more specifically, if this does not help you._
