### ISSUE TITLE
Wie viele CP sollte man im ersten Semester absolvieren?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#64]

**Comment by laura-meyer** [comment]
Es gibt keine feste Vorschrift wie viele CP absolviert werden *müssen*. Vorgesehen sind für jedes Semester 30 CP. Letztendlich kannst du aber selber entscheiden wie viel Arbeit du in das ein oder andere Modul investieren musst - basierend auf deinem Vorwissen oder wie gut du mit den neuen Inhalten zurecht kommst.
