### ISSUE TITLE
Ich hab die O-Woche verschlafen... aeh verpasst, was mach ich nun? 

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#69]

**Comment by laura-meyer** [comment]
In der O-Woche wurden sehr viele Informationen in den verschiedenen Veranstaltungen kommuniziert, was es schwierig macht alles in einer Antwort zusammen zu fassen.
 Versuche vielleicht zunächst deinen Stundenplan zusammen zu stellen und hinterfrage weiteres bei deinen Kommilitonen oder melde dich nochmal direkt bei uns.
