### ISSUE TITLE
Ich habe leider immernoch keinen Zugang auf bzw. meine Daten für (m)einen ARTIST Account erhalten. An wen muss ich mich wenden deswegen?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#70]

**Comment by laura-meyer** [comment]
Wende dich damit am besten an Claudia Keßler.
claudia.kessler@hfk-bremen.de 

Sprechstunde an der HfK: Mi 11-13h, Do 14-16h und nach Vereinbarung; HfK, Am Speicher XI Raum 4.14.050
Sprechstunde an der Uni: Di 12-14h (ab 17.10.2017) und nach Vereinbarung; MZH Raum 1280
