### ISSUE TITLE
Wahlmöglichkeiten für Mastermodul Media Informatics? // Options for master module Media Informatics?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#71]

**Comment by jelko** [comment]
You can pick different classes / lectures for the media informatics module each semester. All MI classes are thought at Uni. Have a look at the [course catalog](http://www.uni-bremen.de/en/studies/lecture-courses/course-catalogue.html?tx_hbulvp_pi1%5Bmodule%5D=4132cbe2326f0683415168a687a1e4ab) to find all your options (courses listed as M-MI). If you can/like to participate in german-speaking classes you can usually pick form the entire course catalog form the informatics department, including bachelor classes.

Beware that you always have the opportunity to get credits for any module in unique / non-standard ways. You can always asked to get credits for other classes in this module or do an independent study.
