### ISSUE TITLE
Ist in der vorlesungsfreien Zeit genug Zeit zum Arbeiten? // Is it possible to work during the semester break?

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#75]

**Comment by jelko** [comment]
Für HfK-Kurse wird in der vorlesungsfreien Zeit meist an der Fertigstellung der Projekte gearbeitet. Da die Einteilung der Zeit aber jedem selbst überlassen ist, besteht in der Regel genug Zeit zum Arbeiten, wenn du viel während des Semester schaffst.

Typische Prüfungen (Klausuren oder Fachgespräche) an der Uni finden in der vorlesungsfreien Zeit statt. Es stehen meist mehrere Termine zur Auswahl. Für die Prüfungsvorbereitung solltest du ca. 2 Wochen einplanen. Darum herum oder nebenher kannst du natürlich arbeiten. Wenn du mehrere Prüfungen kurz hintereinander ablegen willst, solltest du besser "Urlaub" haben.

_For HfK courses the semester break is normally used to finish the projects. However you schedule your time the way you want to so it is definitely possible to work during the semester break, if you get a lot done during the semester._

_Typical exams (written or oral) at Uni are scheduled during the semester break (lecture-free time). For exam you usually have multiple date options. Preparation roughly needs 2 weeks. Of course it is possible to work during this time, if scheduled well. If you are taking multiple exams in short succession it might be good to be on "vacation"._
