### ISSUE TITLE
I missed the orientation week, how can I access the ARTIST ? I did not receive username or password like in UNI


### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#77]

**Comment by laura-meyer** [comment]
Fill the form at the end op this game and wait a few days. (Scroll down for the form) 

In case you are not going to receive them within the next days, contact Claudia Keßler
claudia.kessler@hfk-bremen.de

Office hours at HfK: Wed 11-13h, Thu 14-16h and by arrangement; HfK, Am Speicher XI room 4.14.050
Office hours at Uni: Tue 12-14h (starting 17.10.2017) and by arrangement; MZH room 1280
