### ISSUE TITLE
Your courses for the 2nd semester // Kurse im 2ten Semester

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#80]

**Comment by jelko** [comment]
"Hey! Could you put a link to with master courses for this 2 semester? Thanks a lot!"

Of course! Here you go:

This semesters courses at [Uni](https://www.uni-bremen.de/studium/starten-studieren/veranstaltungsverzeichnis.html?tx_hbulvp_pi1%5Bmodule%5D=4132cbe2326f0683415168a687a1e4ab&tx_hbulvp_pi1%5Bsem%5D=28) and [HfK](https://application.hfk-bremen.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-Au0oLWqyIAKEfNRPYzISrdmdUdCBMGo5B6k4pApGlA726CdzR.Y16121R7xJqksn-tNdpQ-3X.KwGnInqYQh-SLwE2pKx0SWGqDqf83kQdCcseGgE6izch1jfvWJf.xciRmR-mIcoVbbBFPla)
